name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: jackbgrimes/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${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}
          OPENAI_API_KEY: ${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}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
